//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.09 at 09:30:17 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.wcio.org/XML/WCSTAT", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_wcio_org.xml.wcstat;
